# site settings
title: Stacey and John are getting married on 28 May 2022
subtitle: 28 May 2022
email: wedding@johnhayn.es
description:  
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://staceyandjohn.co.uk # the base hostname & protocol for your site
author:
street_address: 
city:
state: 
zip_code: 
country:
phone:
permalink: /:title/

repository: staceyandjohn.github.io/staceyandjohn

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
facebook_url: 
instagram_url: https://www.instagram.com/staceyandjohn/
youtube_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap
  - jekyll-airtable
  - environment_variables_generator

airtable:
  enable_sync: true
  base_uid: 'appp7C1MblPCnMePn'
  airtable_api_key: ${{ secrets.GH_PAGES_TOKEN }}
  tables:
    - name: 'Use Cases' 
    - name: 'Whitepapers'    
    - name: 'Quotes'
      long_text_columns:
        - 'column name'