# site settings
title: Stacey & John Acoustic Duo
subtitle: 2022
email: mail@staceyandjohn.co.uk
description: "Live Acoustic Duo for Events, Parties & Weddings"
baseurl: "" # the subpath of your site, e.g. /blog
url: staceyandjohn.co.uk # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 
permalink: /:title/

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/The-Great-Fire-109788457226542
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://facebook.com/staceyandjohn
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
url: "https://staceyandjohn.co.uk" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap